### ISSUE TITLE
422 Error code

### ISSUE THREAD

**Issue by metallicalfa2** [hwchase17/langchainjs#1329]
I'm using docker-compose to run local chroma DB. While using `from_documents` function, the following error occurs
<img width="974" alt="image" src="https://github.com/hwchase17/langchainjs/assets/16849485/301581b9-643a-4a63-a26f-b6316f1eb101">

**Comment by rohinrohin** [comment]
Me too! It fails in the chroma.fromDocuments, getText, ... function and I think it is related to #1311. I tried to work around this but was not able to successfully. 


Source code: 
<img width="777" alt="CleanShot 2023-05-23 at 19 00 29@2x" src="https://github.com/hwchase17/langchainjs/assets/4285101/77cf5cb8-9ddc-4f64-9f84-0c25e8168c38">

Error: 

```
- error Error: [object Response]
    at ChromaClient.getOrCreateCollection 
```
Any help is appreciated!

**Comment by rodrigo398** [comment]
What version of `ChromaClient` are you using?,  That's happening because there's a mismatch between the `Chroma` version used by `Langchain` and the actual `Chroma` version. In the latest version of `LangChain`, the `getOrCreateCollection` function is being called with only one argument, but Chroma requires three arguments.

```
name: string,
metadata?: CollectionMetadata,
embeddingFunction?: IEmbeddingFunction
```

**Comment by rodrigo398** [comment]
I see the issue I mentioned before was fixed already
https://github.com/hwchase17/langchainjs/pull/1348

**Comment by jacoblee93** [comment]
Can you try updating your Chroma package to > 1.4.2? #1348 should have fixed this.
