### ISSUE TITLE
How to initialize ConversationSummaryMemory with existing summary text

### ISSUE THREAD

**Issue by iamnamitg** [hwchase17/langchainjs#2320]
For a chatbot application, previously I utilized the `BufferMemory` to initialize with the chat history. It was achieved using the `ChatMessageHistory` class as shown:

```
const bufferMemory = new BufferMemory({
    inputKey: "input",
    memoryKey: "chat_history",
    chatHistory: new ChatMessageHistory([{messages}]),
    returnMessages: true,
});
```

Is there an equivalent method to initialize the `ConversationSummaryMemory` with an existing summary?

```
const summaryMemory = new ConversationSummaryMemory({
    llm: new ChatOpenAI({ modelName: "gpt-3.5-turbo", temperature: 0 }),
    inputKey: "input",
    memoryKey: "conversation_summary",
    // Possibly something like this?
    // summary: new ConversationSummary({summaryString}),
});
```

**Comment by iamnamitg** [comment]
In my chatbot app, I aim to retain the user's chat history as a summary if they return to chat later. I will provide this summary to the `ConversationSummaryMemory` when the user initiates a new conversation and continue from there. I want to avoid regenerating the summary using the user's previous chat messages, as it may exceed the model's token limit. Is this possible?

**Comment by iamnamitg** [comment]
Found the fix, the `buffer` property can be assigned after initialization of the `ConversationSummaryMemory`.

```
const summaryMemory = new ConversationSummaryMemory({
    llm: new ChatOpenAI({ modelName: "gpt-3.5-turbo", temperature: 0 }),
    inputKey: "input",
    memoryKey: "conversation_summary",
});

summaryMemory.buffer = "{previous_summary_string}"
```

**Comment by whk6688** [comment]
fisrt, thanks.
then i modify code as you said:
--------------------------------------------------------
prompt = ChatPromptTemplate(
    messages=[
        SystemMessagePromptTemplate.from_template(
            "You are a nice chatbot having a conversation with a human.Provide a direct answer of the question. refer chat history provided and answer according to it."
        ),
        # The `variable_name` here is what must align with memory
        MessagesPlaceholder(variable_name="chat_history"),
        HumanMessagePromptTemplate.from_template("{question}"),
    ]
)

memory = ConversationSummaryMemory(llm=llm,memory_key="chat_history", return_messages=True)


memory.chat_memory.add_user_message("hi, i am Kevin")
memory.chat_memory.add_ai_message("hi, i am nan")

memory.chat_memory.add_user_message("i am late for school")
memory.chat_memory.add_ai_message("oh, sound bad, i hope you can be happier")

memory.chat_memory.add_user_message("in fact, because of mom's mistake, she forgot something always")
memory.chat_memory.add_ai_message("i see, it does not matter, little thing")

memory.chat_memory.add_user_message("ok, let's chat something ")
memory.chat_memory.add_ai_message("sure, i like chat too")

conversation = LLMChain(llm=llm, prompt=prompt, verbose=True, memory=memory)
conversation({"question": "can you tell me why i was late for school"})

------------------
AI answer:I do not have access to your personal information or context, so I cannot determine exactly why you were late for school. It is possible that there may be several reasons for tardiness such as traffic, transportation delays, or simply forgetting the time. Could you please provide more details about your situation?

-----------------------------
I hope AI can answer the question correctly
