### ISSUE TITLE
How to load langchainpy and langchainjs together?

### ISSUE THREAD

**Issue by linonetwo** [hwchase17/langchainjs#436]
https://github.com/logspace-ai/langflow/issues/61#issuecomment-1478880510

Does ecosystem fits?

**Comment by ogabrielluiz** [comment]
Not quite yet. 

This would require a backend that matches what we did in Python. At least the Loading module would have to be implemented. 

One way we can do this is to export it to LangChain and then export the created Chain as JSON. 

In the backend we are processing the graph that comes from React-flow to turn it into a LangChain graph. Since we haven't finished the graph processing algorithm in Python this would require maintenance in two languages. 

Do you see a better approach to this?

**Comment by nfcampos** [comment]
HI, not sure what you mean, could you clarify?

**Comment by linonetwo** [comment]
langflow can only load langchain py, I was asking is there a possibility that they can load langchainjs in their project.
