### ISSUE TITLE
Investigate bundle size

### ISSUE THREAD

**Issue by nfcampos** [hwchase17/langchainjs#809]
Is it tiktoken, or something else?

**Comment by dqbd** [comment]
Hello! 

Looking at the bundle size and metafile when bundled through esbuild + wrangler, the main reason the bundle size is large is due to the big WASM file included by @dqbd/tiktoken. 

The WASM file contains the rankings for all models (~3 MB uncompressed) + the tokenizer logic itself (~700 kB uncompressed). 

Even if ranks only for `gpt-3.5`/`gpt-4` are bundled (skipping older gpt-2 ranks etc.), the `cl100k_base` (1.1 MB uncompressed) + tokenizer fits just right into the 1 MB limit when compressed, not leaving enough space for rest of `langchain`.

I think the best way forward is to either:
- Split the `@dqbd/tiktoken` package into a separate endpoint for the edge. That way, we're not bundling anything. However, as this would be an additional network call, this would be at the expense of slower tokenization. Some preliminary work has been done in that regard, we could release an isomorphic package, which would call an API if imported in edge runtimes.
- Avoid tokenization altogether when just consuming `OpenAI` and other LLMs. This would be harder to do as far as I can see and would most likely be a breaking change. 

---

Adding the analyzed `meta.json` bundle when just importing `OpenAi` LLM. 

<img width="1091" alt="CleanShot 2023-04-15 at 15 17 04@2x" src="https://user-images.githubusercontent.com/1443449/232226197-b1a528da-4724-44d4-8d11-c8daaa655ac7.png">

Note: this is not only related to CF Workers but for all other edge runtimes as well.

**Comment by nfcampos** [comment]
Thanks a lot for this investigation @dqbd 
 
Approach 1 sounds interesting to me, anything I can do to help here?

Approach 2 is harder as the tokeniser is eg used deep inside some chains, so not terribly clear how to make it more optional. 

That said, we could conceivably move the countTokens methods outside of the LLM classes so that they need to be imported separately, I'd be okay with that, I don't think many people are using them directly. 

What's harder is 
1. The chains that use it, those would need to be moved to separate endpoints from other chains
2. The maxTokens=-1 behaviour on OpenAI LLM which uses the tokeniser to calculate max tokens, that'd be harder to remove

but I would however be perfectly okay with making it require a remote download when used as you suggested 

thoughts?

**Comment by protoEvangelion** [comment]
Thanks @dqbd I'm seeing something similar when running cloudflare worker cli:

```
wrangler publish --dry-run --outdir dist
```

![image](https://user-images.githubusercontent.com/20076677/236099296-ce0934a6-5e48-41a9-9140-16587e01e71d.png)

I like your first idea as well. To accomplish this, are you referring to the [suggestion](https://developers.cloudflare.com/workers/wrangler/bundling/#files-which-will-not-be-bundled) by cloudflare here?

I see [Denoflare has a way](https://denoflare.dev/reference/wasm#module-based-workers) to import a wasm file via url:

```javascript
import { importWasm } from 'https://raw.githubusercontent.com/skymethod/denoflare/v0.5.11/common/import_wasm.ts';
const module = await importWasm(import.meta.url, './hello.wasm');
```

But I don't see a way in Cloudflare to accomplish the same. **_How would you suggest making that happen?_**
