### ISSUE TITLE
Store and Reuse alculated embeddings

### ISSUE THREAD

**Issue by domenicomanna** [hwchase17/langchainjs#869]
Is it possible to export the calculated embeddings for a set of documents and store them so they don't need to be calculated again? Please see below snippet for an example of what I mean:

```
// calculate embeddings for the first time
const textSplitter = new RecursiveCharacterTextSplitter({ chunkSize: 1000 });
const documents = await textSplitter.createDocuments([stateOfTheUnionText]);
const vectorStore = await MemoryVectorStore.fromDocuments(
  documents,
  new OpenAIEmbeddings()
);

// now that the embeddings have been calculated, let's store and reuse them so we don't need to recalculate them
localStorage.setItem('embeddings', vectorStore.embeddings);
const storedEmbeddings = JSON.parse(localStorage.getItem('embeddings'));
const memoryVectorStore = await MemoryVectorStore.fromDocuments(documents, storedEmbeddings);
```

**Comment by domenicomanna** [comment]
accidentally creating two issues for this. closing this one and linking the other one: https://github.com/hwchase17/langchainjs/issues/870

**Comment by kitfit-dave** [comment]
The VectorStore.embeddings is not the "actual" embedding vectors, but really an "embedder" - a ref to (in this case) the openAI API that the store can call to create the embeddings (the vectors)

If you want to store the vectors that were generated, you can call embeddings.embedDocuments yourself, you then have the vectors (to save and load if you like), and you can call VectorStore.addVectors (rather than fromDocuments - which eventually calls addVectors anyway)

But if you are doing this to "re-use" some of the work done in calling fromDocuments, why not re-use the createDocuments work too? I would be looking for a way to save and re-load the MemoryVectorStore. MemoryVectorStore holds the store data in memoryVectors, so it looks like something like this should work:

```
const embeddings = new OpenAIEmbeddings({ openAIApiKey: process.env.OPENAI_API_KEY })
const memoryVectors = JSON.parse(localStorage.getItem('memoryVectors') ?? 'null')
let vectorStore
if (memoryVectors) {
	vectorStore = await MemoryVectorStore.fromExistingIndex(embeddings)
	vectorStore.memoryVectors = memoryVectors
} else {
	vectorStore = await MemoryVectorStore.fromDocuments(docs, embeddings)
	localStorage.setItem('memoryVectors', JSON.stringify(vectorStore.memoryVectors))
}
// whatever you wanted to do, e.g.
const similarDocs = await vectorStore.similaritySearch(query)
```
note: that there is a limit to what can be stored in localStorage (maybe 5MB but it depends)

**Comment by domenicomanna** [comment]
awesome, this is exactly what I was looking for. thank you so much!
